# NEEDS API KEY FROM ALPACA FINNHUB AND OPENAI TO WORK

ALPACA_API_KEY = 'INSERT KEY HERE'
ALPACA_API_SECRET_KEY = 'INSERT KEY HERE'

MAIN_WATCHLIST_ID = 'INSERT KEY HERE'

BASE_URL = 'https://paper-api.alpaca.markets'


FINNHUB_API_KEY = "INSERT KEY HERE"

OPEN_AI_API_KEY = 'INSERT KEY HERE'

# FILL IN WITH STOCK TICKERS INTERESTED IN ANALYZING 
stocks_of_interest = ['AAPL','MSFT','AMZN','NVDA','GOOGL','META','GOOG','TSLA','BRK.B','AVGO']
